import numpy as np
from CostFunctions import ann_node_count_fitness, ann_weights_fitness_function, griewank, penalized1, rastrigin, rosenbrock, schwefel, sphere, step
from keras.layers import Dense
from keras.models import Sequential


def create_model():
    num_nodes_per_layer = [
        6,
        6,
        6,
    ]
    model = Sequential()
    model.add(Dense(num_nodes_per_layer[0],
              activation="relu", input_shape=(6,)))

    for nodes in num_nodes_per_layer[1:]:
        model.add(Dense(nodes, activation="relu"))

    model.add(Dense(2))

    model.compile(optimizer="adam", loss="mse", metrics=["accuracy"])
    total_num_weights = sum(np.prod(w.shape) for w in model.get_weights()[::2])
    total_num_biases = sum(np.prod(b.shape) for b in model.get_weights()[1::2])
    ann_dimensions = total_num_weights + total_num_biases

    return model, ann_dimensions


pso_options = [{
    "function": sphere,
    "function_name": "Sphere",
    "position_bounds": (-100, 100),
    "velocity_bounds": (-40, 40),
    "threshold": 0.01,
    "num_particles": 3,
    "num_dimensions": 3,
    "Cp_min": 0.5,
    "Cp_max": 2.5,
    "Cg_min": 0.5,
    "Cg_max": 2.5,
    "w_min": 0.4,
    "w_max": 0.9,
    "inertia": 0.9,
    "c1": 2.0,
    "c2": 2.0,
},
    {
        "function": rosenbrock,
        "function_name": "Rosenbrock",
        "position_bounds": (-30, 30),
        "velocity_bounds": (-12, 12),
        "threshold": 100,
        "num_particles": 3,
        "num_dimensions": 3,
        "Cp_min": 0.5,
        "Cp_max": 2.5,
        "Cg_min": 0.5,
        "Cg_max": 2.5,
        "w_min": 0.4,
        "w_max": 0.9,
        "inertia": 0.9,
        "c1": 2.0,
        "c2": 2.0,
},
    {
        "function": rastrigin,
        "function_name": "Rastrigin",
        "position_bounds": (-5.12, 5.12),
        "velocity_bounds": (-2.048, 2.048),
        "threshold": 50,
        "num_particles": 30,
        "num_dimensions": 30,
        "Cp_min": 0.5,
        "Cp_max": 2.5,
        "Cg_min": 0.5,
        "Cg_max": 2.5,
        "w_min": 0.4,
        "w_max": 0.9,
        "inertia": 0.9,
        "c1": 2.0,
        "c2": 2.0,
},
    {
        "function": schwefel,
        "function_name": "Schwefel",
        "position_bounds": (-100, 100),
        "velocity_bounds": (-40, 40),
        "threshold": 0.01,
        "num_particles": 30,
        "num_dimensions": 30,
        "Cp_min": 0.5,
        "Cp_max": 2.5,
        "Cg_min": 0.5,
        "Cg_max": 2.5,
        "w_min": 0.4,
        "w_max": 0.9,
        "inertia": 0.9,
        "c1": 2,
        "c2": 2,
},
    {
        "function": griewank,
        "function_name": "Griewank",
        "position_bounds": (-600, 600),
        "velocity_bounds": (-240, 240),
        "threshold": 0.01,
        "num_particles": 30,
        "num_dimensions": 30,
        "Cp_min": 0.5,
        "Cp_max": 2.5,
        "Cg_min": 0.5,
        "Cg_max": 2.5,
        "w_min": 0.4,
        "w_max": 0.9,
        "inertia": 0.9,
        "c1": 2,
        "c2": 2,
},
    {
        "function": penalized1,
        "function_name": "Penalized1",
        "position_bounds": (-50, 50),
        "velocity_bounds": (-20, 20),
        "threshold": 0.01,
        "num_particles": 3,
        "num_dimensions": 3,
        "Cp_min": 0.5,
        "Cp_max": 2.5,
        "Cg_min": 0.5,
        "Cg_max": 2.5,
        "w_min": 0.4,
        "w_max": 0.9,
        "inertia": 0.9,
        "c1": 1.49445,
        "c2": 1.49445,
},
    {
        "function": step,
        "function_name": "Step",
        "position_bounds": (-100, 100),
        "velocity_bounds": (-40, 40),
        "threshold": 0.01,
        "num_particles": 3,
        "num_dimensions": 3,
        "Cp_min": 0.5,
        "Cp_max": 2.5,
        "Cg_min": 0.5,
        "Cg_max": 2.5,
        "w_min": 0.4,
        "w_max": 0.9,
        "inertia": 0.9,
        "c1": 1.49445,
        "c2": 1.49445,
},
    {
        "function": ann_node_count_fitness,
        "function_name": "ANN Node Count RPSO",
        "position_bounds": (1, 100),
        "velocity_bounds": (-40, 40),
        "threshold": 1,
        "num_particles": 3,
        "num_dimensions": 3,
        "Cp_min": 0.5,
        "Cp_max": 2.5,
        "Cg_min": 0.5,
        "Cg_max": 2.5,
        "w_min": 0.4,
        "w_max": 0.9,
},
    {
        "function": ann_node_count_fitness,
        "function_name": "ANN Node Count Gbest",
        "position_bounds": (1, 100),
        "velocity_bounds": (-40, 40),
        "threshold": 1,
        "num_particles": 3,
        "num_dimensions": 3,
        "inertia": 0.9,
        "c1": 1.49445,
        "c2": 1.49445,
},
    {
        "function": ann_weights_fitness_function,
        "function_name": "ANN Weights and biases gbest",
        "position_bounds": (-1.0, 1.0),
        "velocity_bounds": (-0.2, 0.2),
        "threshold": 1,
        "num_particles": 6,
        "inertia": 0.9,
        "c1": 1.49445,
        "c2": 1.49445,
},
    {
        "function": ann_weights_fitness_function,
        "function_name": "ANN Weights and biases rpso",
        "position_bounds": (-1.0, 1.0),
        "velocity_bounds": (-0.2, 0.2),
        "threshold": 1,
        "num_particles": 6,
        "Cp_min": 0.1,
        "Cp_max": 3.5,
        "Cg_min": 0.9,
        "Cg_max": 1.5,
        "w_min": 0.8,
        "w_max": 2.0,
        "gwn_std_dev": 0.07,
},]
